import {
  EstadoEstudio,
  Prioridad,
  Rol,
  TipoEstudio,
  type Estudio,
  type HistorialEstudio,
  type Paciente,
  type Radiologo,
  type Usuario,
} from "@/types";

// ─── Usuarios ────────────────────────────────────────────────────────────────

export const mockUsuarios: Usuario[] = [
  { id: "u1", email: "admin@mediestudios.com",      rol: Rol.ADMIN,       activo: true },
  { id: "u2", email: "secretario@mediestudios.com", rol: Rol.SECRETARIO,  activo: true },
  { id: "u3", email: "carlos.ruiz@mediestudios.com",  rol: Rol.RADIOLOGO, activo: true },
  { id: "u4", email: "laura.benitez@mediestudios.com", rol: Rol.RADIOLOGO, activo: true },
  { id: "u5", email: "martin.silva@mediestudios.com",  rol: Rol.RADIOLOGO, activo: false },
];

// ─── Radiólogos ───────────────────────────────────────────────────────────────

export const mockRadiologos: Radiologo[] = [
  {
    id: "r1",
    usuarioId: "u3",
    nombre: "Carlos",
    apellido: "Ruiz",
    telefono: "1145001122",
    activo: true,
    estudiosAsignados: 3,
    estudiosInformados: 14,
  },
  {
    id: "r2",
    usuarioId: "u4",
    nombre: "Laura",
    apellido: "Benítez",
    telefono: "1167334455",
    activo: true,
    estudiosAsignados: 1,
    estudiosInformados: 9,
  },
  {
    id: "r3",
    usuarioId: "u5",
    nombre: "Martín",
    apellido: "Silva",
    activo: false,
    estudiosAsignados: 0,
    estudiosInformados: 22,
  },
];

// ─── Pacientes ────────────────────────────────────────────────────────────────

export const mockPacientes: Paciente[] = [
  {
    id: "p1",
    nombre: "María",
    apellido: "López",
    dni: "30123456",
    fechaNacimiento: "1985-03-12",
    telefono: "1145678901",
    creadoEn: "2026-01-10T09:00:00Z",
    cantidadEstudios: 2,
  },
  {
    id: "p2",
    nombre: "Juan",
    apellido: "Martínez",
    dni: "25987654",
    fechaNacimiento: "1972-07-28",
    telefono: "1167890123",
    creadoEn: "2026-02-03T11:30:00Z",
    cantidadEstudios: 2,
  },
  {
    id: "p3",
    nombre: "Sofía",
    apellido: "Fernández",
    dni: "40234567",
    fechaNacimiento: "1998-11-05",
    creadoEn: "2026-03-15T14:00:00Z",
    cantidadEstudios: 1,
  },
  {
    id: "p4",
    nombre: "Roberto",
    apellido: "García",
    dni: "18765432",
    fechaNacimiento: "1960-04-22",
    telefono: "1122334455",
    creadoEn: "2026-04-01T08:45:00Z",
    cantidadEstudios: 2,
  },
  {
    id: "p5",
    nombre: "Elena",
    apellido: "Torres",
    dni: "35678901",
    fechaNacimiento: "1991-09-17",
    creadoEn: "2026-05-05T10:15:00Z",
    cantidadEstudios: 1,
  },
];

// ─── Estudios ─────────────────────────────────────────────────────────────────

export const mockEstudios: Estudio[] = [
  {
    id: "e1",
    pacienteId: "p1",
    paciente: mockPacientes[0],
    radiologoId: "r1",
    radiologo: mockRadiologos[0],
    tipoEstudio: TipoEstudio.RADIOGRAFIA,
    linkEstudio: "https://storage.mediestudios.com/e1/rx-torax.zip",
    fechaEstudio: "2026-05-10",
    estado: EstadoEstudio.INFORMADO,
    prioridad: Prioridad.NORMAL,
    cargadoPorId: "u2",
    creadoEn: "2026-05-10T08:20:00Z",
    informadoEn: "2026-05-11T16:00:00Z",
  },
  {
    id: "e2",
    pacienteId: "p2",
    paciente: mockPacientes[1],
    tipoEstudio: TipoEstudio.ECOGRAFIA,
    linkEstudio: "https://storage.mediestudios.com/e2/eco-abdomen.zip",
    fechaEstudio: "2026-05-17",
    estado: EstadoEstudio.PENDIENTE,
    prioridad: Prioridad.URGENTE,
    observaciones: "Paciente con dolor abdominal agudo.",
    cargadoPorId: "u2",
    creadoEn: "2026-05-17T09:05:00Z",
  },
  {
    id: "e3",
    pacienteId: "p3",
    paciente: mockPacientes[2],
    radiologoId: "r2",
    radiologo: mockRadiologos[1],
    tipoEstudio: TipoEstudio.TOMOGRAFIA,
    linkEstudio: "https://storage.mediestudios.com/e3/tac-torax.zip",
    fechaEstudio: "2026-05-16",
    estado: EstadoEstudio.ASIGNADO,
    prioridad: Prioridad.NORMAL,
    cargadoPorId: "u2",
    creadoEn: "2026-05-16T10:30:00Z",
  },
  {
    id: "e4",
    pacienteId: "p4",
    paciente: mockPacientes[3],
    radiologoId: "r1",
    radiologo: mockRadiologos[0],
    tipoEstudio: TipoEstudio.RESONANCIA,
    linkEstudio: "https://storage.mediestudios.com/e4/rm-columna.zip",
    fechaEstudio: "2026-05-08",
    estado: EstadoEstudio.INFORMADO,
    prioridad: Prioridad.NORMAL,
    observaciones: "Control post-quirúrgico columna lumbar.",
    cargadoPorId: "u2",
    creadoEn: "2026-05-08T07:50:00Z",
    informadoEn: "2026-05-09T14:30:00Z",
  },
  {
    id: "e5",
    pacienteId: "p5",
    paciente: mockPacientes[4],
    tipoEstudio: TipoEstudio.RADIOGRAFIA,
    linkEstudio: "https://storage.mediestudios.com/e5/rx-mano.zip",
    fechaEstudio: "2026-05-18",
    estado: EstadoEstudio.PENDIENTE,
    prioridad: Prioridad.NORMAL,
    cargadoPorId: "u2",
    creadoEn: "2026-05-18T08:00:00Z",
  },
  {
    id: "e6",
    pacienteId: "p1",
    paciente: mockPacientes[0],
    radiologoId: "r1",
    radiologo: mockRadiologos[0],
    tipoEstudio: TipoEstudio.ECOGRAFIA,
    linkEstudio: "https://storage.mediestudios.com/e6/eco-tiroides.zip",
    fechaEstudio: "2026-05-15",
    estado: EstadoEstudio.ASIGNADO,
    prioridad: Prioridad.URGENTE,
    observaciones: "Nódulo tiroideo detectado en control previo.",
    cargadoPorId: "u2",
    creadoEn: "2026-05-15T11:00:00Z",
  },
  {
    id: "e7",
    pacienteId: "p2",
    paciente: mockPacientes[1],
    radiologoId: "r2",
    radiologo: mockRadiologos[1],
    tipoEstudio: TipoEstudio.RESONANCIA,
    linkEstudio: "https://storage.mediestudios.com/e7/rm-rodilla.zip",
    fechaEstudio: "2026-05-12",
    estado: EstadoEstudio.INFORMADO,
    prioridad: Prioridad.URGENTE,
    cargadoPorId: "u2",
    creadoEn: "2026-05-12T13:00:00Z",
    informadoEn: "2026-05-13T09:00:00Z",
  },
  {
    id: "e8",
    pacienteId: "p4",
    paciente: mockPacientes[3],
    tipoEstudio: TipoEstudio.TOMOGRAFIA,
    linkEstudio: "https://storage.mediestudios.com/e8/tac-cerebro.zip",
    fechaEstudio: "2026-05-18",
    estado: EstadoEstudio.PENDIENTE,
    prioridad: Prioridad.URGENTE,
    observaciones: "Cefalea intensa de inicio brusco.",
    cargadoPorId: "u2",
    creadoEn: "2026-05-18T07:30:00Z",
  },
];

// ─── Historial ────────────────────────────────────────────────────────────────

export const mockHistorial: HistorialEstudio[] = [
  {
    id: "h1",
    estudioId: "e3",
    usuarioId: "u1",
    usuario: mockUsuarios[0],
    campoModificado: "estado",
    valorAnterior: EstadoEstudio.PENDIENTE,
    valorNuevo: EstadoEstudio.ASIGNADO,
    fecha: "2026-05-16T12:00:00Z",
  },
  {
    id: "h2",
    estudioId: "e1",
    usuarioId: "u3",
    usuario: mockUsuarios[2],
    campoModificado: "estado",
    valorAnterior: EstadoEstudio.ASIGNADO,
    valorNuevo: EstadoEstudio.INFORMADO,
    fecha: "2026-05-11T16:00:00Z",
  },
  {
    id: "h3",
    estudioId: "e6",
    usuarioId: "u1",
    usuario: mockUsuarios[0],
    campoModificado: "prioridad",
    valorAnterior: Prioridad.NORMAL,
    valorNuevo: Prioridad.URGENTE,
    fecha: "2026-05-15T11:45:00Z",
  },
  {
    id: "h4",
    estudioId: "e6",
    usuarioId: "u1",
    usuario: mockUsuarios[0],
    campoModificado: "estado",
    valorAnterior: EstadoEstudio.PENDIENTE,
    valorNuevo: EstadoEstudio.ASIGNADO,
    fecha: "2026-05-15T11:50:00Z",
  },
  {
    id: "h5",
    estudioId: "e4",
    usuarioId: "u3",
    usuario: mockUsuarios[2],
    campoModificado: "estado",
    valorAnterior: EstadoEstudio.ASIGNADO,
    valorNuevo: EstadoEstudio.INFORMADO,
    fecha: "2026-05-09T14:30:00Z",
  },
  {
    id: "h6",
    estudioId: "e7",
    usuarioId: "u4",
    usuario: mockUsuarios[3],
    campoModificado: "estado",
    valorAnterior: EstadoEstudio.ASIGNADO,
    valorNuevo: EstadoEstudio.INFORMADO,
    fecha: "2026-05-13T09:00:00Z",
  },
];
